# Generated by Django 3.2.5 on 2021-07-05 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='date',
            field=models.CharField(blank=True, default='05/July/2021', max_length=10),
        ),
        migrations.AlterField(
            model_name='message',
            name='createdAt',
            field=models.CharField(blank=True, default='07:07 AM', max_length=10),
        ),
        migrations.AlterField(
            model_name='message',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='room',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
