# Generated by Django 3.2.5 on 2021-07-05 03:06

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_room_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='createdAt',
            field=models.CharField(blank=True, default='08:07 AM', max_length=10),
        ),
        migrations.AlterField(
            model_name='message',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.room'),
        ),
        migrations.AlterField(
            model_name='room',
            name='datetime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 7, 5, 8, 36, 57, 78732)),
        ),
    ]
