# Generated by Django 3.2.5 on 2021-07-05 03:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_auto_20210705_0848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='datetime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 7, 5, 8, 48, 9, 702201)),
        ),
    ]
