# Generated by Django 3.2.5 on 2021-07-05 03:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_alter_room_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='date',
            field=models.CharField(blank=True, default='05/July/2021', max_length=20),
        ),
        migrations.AlterField(
            model_name='room',
            name='datetime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 7, 5, 8, 50, 41, 865157)),
        ),
    ]
