# Generated by Django 3.2.5 on 2021-07-05 03:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_auto_20210705_0850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='createdAt',
            field=models.CharField(blank=True, default='09:29 AM', max_length=10),
        ),
        migrations.AlterField(
            model_name='room',
            name='datetime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 7, 5, 9, 29, 2, 28346)),
        ),
    ]
